#!/bin/bash
BASE_DIR=$(dirname "$0")
DIST_DIR=$BASE_DIR/../dist
CONFIG_FILE_DEFAULT="aws"
CONFIG_FILE_TYPE="s3dist.config"
PROFILE="default"
S3_BUCKET=""

# Check if aws-cli is installed
if command -v aws 2>&1 | grep -q 'aws' ; then
  :
else
  echo "The aws-cli installation is missing."; exit 1
fi

# Reading out the optional flags
while getopts c flag
do
    case "${flag}" in
        c)  CONFIG_FILE_NAME=${OPTARG};;
        p)  PROFILE=${OPTARG};;
        d)  DIST_DIR=${OPTARG};;
        b)  S3_BUCKET=${OPTARG};;
        r)  AWS_REGION=${OPTARG};;
        a)  ACCESS_KEY=${OPTARG};;
        s)  SECRET_KEY=${OPTARG};;
        g)  GITIGNORE=${OPTARG};;
        y)  YES=true;;
    esac
done

# If the cinfig file exists, read its content
if test -f "$CONFIG_FILE"; then
  while IFS= read -r ROW
  do
    params=(${ROW//=/ })
    case "${params[0]}" in
      PROFILE)
        PROFILE=${params[1]}
        ;;
      DIST_DIR)
        DIST_DIR="$BASE_DIR/../${params[1]}"
        ;;
      S3_BUCKET)
        S3_BUCKET=${params[1]} 
        ;;
    esac 
  done < "$CONFIG_FILE"
else
  echo "No config file found. Run aws_configure to create it!"; exit 1
fi

echo "AWS profile used: $PROFILE"
echo "S3 Bucket: $S3_BUCKET"

# Getting the region from the profile
AWS_REGION=`aws configure get region --profile $PROFILE`
echo "AWS region: $AWS_REGION"

# Checking whether the bucket exists on S3 and reachable with the given profile
if aws s3 ls $S3_BUCKET --profile $PROFILE  2>&1 | grep -q 'NoSuchBucket' ; then
  echo "The given S3 bucket does not exists or not reachable with the credentials set in the profile '$PROFILE!'"; exit 1
else
  echo "Starting the sync..."
fi

# Sync the dist files to S3
if aws s3 sync $DIST_DIR s3://$S3_BUCKET --profile $PROFILE --delete --acl public-read | grep -q "error"; then
  echo "File sync failed!"; exit 1
else
  echo "Synchronisation successful. Your site is uploaded."
  echo "Site URL: http://${S3_BUCKET}.s3-website.${AWS_REGION}.amazonaws.com"
fi

exit 0